### ISSUE TITLE
Error in diagnosis.py

### ISSUE THREAD

**Issue by Alvarez-P** [aaaimx/covid19-assistant-api#5]
# Error al ejecutar la función get_diagnosis
![image](https://user-images.githubusercontent.com/44200540/77566507-5ee81900-6e8b-11ea-9805-c28061f5f6b8.png)

## Linea en la que marca error
![image](https://user-images.githubusercontent.com/44200540/77566606-86d77c80-6e8b-11ea-9398-1fe270f561bd.png)

**Comment by rnovec** [comment]
Closed. Fixed in #6
